version: "3.9"

# Shared volume
volumes:
  shared-workspace:
    name: "hadoop-distributed-filesystem"
    driver: local

services:
  # Jupyter Lab
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace

  # Spark master
  spark-master:
    image: spark-master
    ports:
      - 5050:5050
      - 7077:7077 # spark master default port
    volumes:
      - shared-workspace:/opt/workspace

  # Spark workers
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 5051:5051
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 5052:5051
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
